---
version: "3.4"
services:
  frontend:
    build:
      context: .
      dockerfile: ${FRONTEND_DOCKERFILE:-Dockerfile}
    ports:
      # allow override of target and published port
      - ${P_PORT:-8000}:${T_PORT:-8000}
    volumes:
      - ./:/opt/app
    env_file:
      # Reuse .env from CRA
      - .env
